services:
  entity-framework-triggers-test:
    build:
      context: .
      dockerfile: EntityFrameworkTriggersTest/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__BloggingDatabase=Server=sqlserver;Database=tulip;User Id=sa;Password=mySuperStrong_pa55word!!!;TrustServerCertificate=true;
    networks:
      - db-triggers-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: mySuperStrong_pa55word!!!
    ports:
      - "1433:1433"
    volumes:
      - ./dockerdata:/var/opt/mssql
    networks:
      - db-triggers-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "mySuperStrong_pa55word!!!" -C
      interval: "2s"
      retries: 10

networks:
  db-triggers-network:
